[build]
  functions = "netlify/functions"
  command = "mkdir -p dist && cp index.html dist/ && cp _redirects dist/"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"

[functions]
  node_bundler = "esbuild"
  directory = "netlify/functions"

[dev]
  functions = "netlify/functions"
  publish = "dist"
  command = "npm run dev"

# Environment variables for development
# Add these in Netlify dashboard or use .env file locally
[context.production.environment]
  NODE_ENV = "production"

[context.deploy-preview.environment]
  NODE_ENV = "staging"

[context.branch-deploy.environment]
  NODE_ENV = "development"

# Headers for security
[[headers]]
  for = "/api/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Redirects for webhook endpoint
[[redirects]]
  from = "/webhook"
  to = "/.netlify/functions/webhook"
  status = 200

[[redirects]]
  from = "/api/summary"
  to = "/.netlify/functions/summary-scheduler"
  status = 200